### ISSUE TITLE
Running Molecule against an IP address instead of created platform for converge / verify / lint?

### ISSUE THREAD

**Issue by nickjj** [ansible/molecule#1518]
# Issue Type

- Feature request / question

##### Molecule installation method:

- pip

##### Ansible installation method:

- pip

## Use case / environment

I'm currently running Windows 10 Pro and make heavy usage of WSL (Bash on Windows, Ubuntu 16). This is where I have Ansible and Molecule installed to. I also have Docker installed with Docker for Windows and configured WSL to remotely connect to that Docker host.

In addition to that I have Vagrant installed in Windows (outside of WSL, since it doesn't work there). I use Hyper-V as a Vagrant provider to manually provision a VM which is where I run my Ansible playbooks against. All I do is supply the IP address of the VM in my Ansible inventory.

## The problem: Molecule is slow with this environment

I'm new to Molecule but set things up to use the Docker "instance" platform, however running Molecule against that is painfully slow, but it's worth pointing out I have been using Docker since 2014 and I have a bunch of Rails, Flask, Phoenix and Node apps Dockerized and Docker is not slow at all for me in those situations.

Running Molecule while it's pip installed, or using the official Docker image is roughly the same speed, both are equally slow within +/- 5%.

### Slowness, measured

With the above set up I took one of my roles and ran `molecule converge` against it, and then I ran converge again to do a 0 change Ansible run. This entire process took 58 seconds. This is with no tests too, just time spent going through the role's tasks.

Then I used Vagrant (which I ran from Windows to provision an Ubuntu 18 box backed by Hyper-V) and ran Ansible against it without Molecule. I ran the same role and then ran it again to do an identical 0 change Ansible run. This time it took 18 seconds.

The "action: create" step of Molecule finishes in like 1 second, so 57 of those seconds are spent running the role in Docker vs 18 seconds with the VM approach. That's 70% slower, and truth be told, that's too slow to use for day to day usage.

**Edit:** I think Molecule might be slowing things down a lot for other reasons too. I took the same Docker image I was using to converge with when using Molecule and then ran it manually outside of Molecule. Then I ran the same playbook I ran against Molecule and it took 28 seconds inside of the non-Molecule Docker container.

So to recap, that's 57 seconds using Docker *with* Molecule, 28 seconds using Docker *without* Molecule and 18 seconds using a VM without Molecule.

### Technical limitations?

Since Vagrant can't be launched from WSL and Molecule is installed in WSL, I don't think having Molecule provision the VM is ever going to work, especially since I have Vagrant installed in Windows (outside of Molecule's environment) and configured to use Hyper-V and not Virtualbox which as far as I know isn't supported by Molecule anyways. This is also a mandatory requirement because you can't have Hyper-V and Virtualbox installed at the same time on Windows and Docker for Windows uses Hyper-V.

## Feature request

For quickly converging, verifying or linting a role I think there's a huge win to be able to just provide a direct IP address to connect to and skip the create step. This way I can use Molecule to test roles through a Hyper-V backed VM that I provisioned myself with Vagrant.

Then when it comes to CI, I can use the Docker instance platform and it's all good.

Is doing that possible today? If so, please include a fully working config, since I only have like 1 hour of experience with Molecule.

**Comment by nickjj** [comment]
After extensive searching I think the delegated driver will allow this but I'm not sure how to set it up because the docs don't include this use case.

Let's say I can ssh into a server by running `ssh nick@192.168.1.42` and all I want Molecule to do is convert, verify and lint a role against that server while skipping the create/destroy actions. What would my `molecule.yml` look like to do that?

**Comment by rmachuca89** [comment]
Hello @nickjj struggling with this one too (a little more complex one, because I was expecting ansible **dynamic inventory script** support into `molecule`, but it seems it won't be supported (at least yet) according to #956 ) but I got it to work with manual configuration of SSH (instead of using my custom tool / script which generates the ansible inventory data from a centralized DB).

The rationale is the following:

- The [delegated driver](https://molecule.readthedocs.io/en/latest/configuration.html#delegated) expects you to manage everything (deserved) regarding the provisioning and the connection
- It means you should be able to just do as you mention (`ssh username@hostname`) with a pre-authorized keys already setup

With that in mind, and according to the previous docs and some examples of the `molecule.yml` from the source code ([e.g this one](https://github.com/ansible/molecule/blob/master/test/scenarios/driver/delegated/molecule/vagrant/molecule.yml)), this implies setting a working **SSH Configuration File**

I got my configuration to work by doing the following (changing real names, and IPs ti avoid any nasty surprises):

1. Setup the related SSH Config file in a general location.

```
# file: /tmp/ssh-config
Host my-delegated-host
    Hostname XXX.XXX.XXX.XXX
    User my-ansible-user
    IdentityFile /path/to/your/private/key
```

2. Perform all required tasks to create and provision your target host with the corresponding **private keys**. (e.g. `ssh-copy-id user@hostname`)

3.  Do a manual test / simulation on how `molecule` should execute it

```
$ ssh my-delegated-host -F /tmp/ssh-config "uname -nsr"
```

4. Validate that your `molecule.yml` points to the staged files and names in the previous steps. e.g

```yaml
...
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'ssh {instance} -F /tmp/ssh-config'
    ansible_connection_options:
      connection: ssh
      ansible_ssh_common_args: -F /tmp/ssh-config
...
platforms:
  - name: my-delegated-host
...
```
5. Finally, perform a `molecule` command that should connect to it (e.g. `verify`) to validate it works:

```
$ molecule verify --scenario-name "delegated-default"
--> Validating schema /home/myuser/projects/myproject/molecule/delegated-default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── delegated-default
    └── verify

--> Scenario: 'delegated-default'
--> Action: 'verify'
--> Executing Testinfra tests found in /home/myuser/projects/myproject/molecule/delegated-default/../resources/tests//...
    ============================= test session starts ==============================
    platform linux -- Python 3.7.0, pytest-4.1.0, py-1.7.0, pluggy-0.8.0 -- /home/myuser/.local/share/virtualenvs/mypoject/bin/python3.7
    rootdir: /home/myuser/projects/myproject/molecule, inifile:
    plugins: testinfra-1.16.0
collected 1 item                                                               

    ../resources/tests/test_default.py::test_hosts_file[ansible:/my-delegated-host] PASSED [100%]
    
    ========================== 1 passed in 21.02 seconds ===========================
Verifier completed successfully.
```

Please take a look into this and let me know if that works for you or if there is something else I can help with.

Regards,

**Comment by ssbarnea** [comment]
Molecule Vagrant driver was moved to https://github.com/pycontribs/molecule-vagrant/issues and if this issue is still valid, please raise a ticket there. Thanks.
