### ISSUE TITLE
LXC dependency used should be replaced

### ISSUE THREAD

**Issue by webknjaz** [ansible/molecule#1580]
# Issue Type

- Bug report

# Desired Behavior

lxc driver backend should be stable and support both Python branches

# Actual Behaviour

lxc-python2 seems to be alpha-quality, unmaintained and is python2-only

**Comment by ssbarnea** [comment]
I totally agree with this as the recent adding of it broke my molecule development wrokflow on MacOS where there the module does not compile because there are no header files.

There are far too many problems related to use of `lxc-python2` and we need to be sure that if a user clones molecule and tries to run `tox`, he will not endup with a situation where packages fails to install.

I did raise https://github.com/Homebrew/brew/issues/5326 to ask for lxc headers but even if this may be sorted in the future I really doubt that a lxc-python2 module is going to updated. Last release was back in 2015 and next year py2 is dropped... 

If the module is still needed for some platform specific parts, we should be sure that we install it only on supported platforms and that we do skip lxc tests on non-supported platforms.

**Comment by webknjaz** [comment]
Yea, so there's two repos with lxc binding under their org. one for py2 and the other is for py3. from what I understood, it looks like somebody from community put `lxc-python2` to PyPI and they don't have the intention to tackle it themselves, but OTOH it looks like they're open to accepting some help with that.

So theoretically it's not hard to help them to build autopublishing to pypi + manylinux1 wheels should they be up to it.
