### ISSUE TITLE
Multiple Molecule Converge runs fail with 8989 Bus Error

### ISSUE THREAD

**Issue by predatorian3** [ansible/molecule#1721]
# Issue Type

- Bug report

# Molecule and Ansible details

```
user01@M1711732 [10:03:43] ~/Documents/development/Ansible/concourse_ci  [master]
$ ansible --version && molecule --version
ansible 2.7.6
  config file = /Users/user01/.ansible.cfg
  configured module search path = ['/Users/user01/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/user01/.pyenv/versions/3.7.2/lib/python3.7/site-packages/ansible
  executable location = /Users/user01/.pyenv/versions/3.7.2/bin/ansible
  python version = 3.7.2 (default, Jan 22 2019, 09:35:39) [Clang 9.0.0 (clang-900.0.39.2)]
molecule, version 2.19.0
user01@M1711732 [10:03:48] ~/Documents/development/Ansible/concourse_ci  [master]
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G1710
user01@M1711732 [10:03:50] ~/Documents/development/Ansible/concourse_ci  [master]
$ uname -a
Darwin M1711732 16.7.0 Darwin Kernel Version 16.7.0: Sun Oct 28 22:30:19 PDT 2018; root:xnu-3789.73.27~1/RELEASE_X86_64 x86_64
user01@M1711732 [10:03:52] ~/Documents/development/Ansible/concourse_ci  [master]
$ vagrant version
Installed Version: 2.1.5
user01@M1711732 [10:07:16] ~/Documents/development/Ansible/concourse_ci  [master]
$ VBoxManage --version
5.1.28r117968
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

> Please give some details of the feature being requested or what should happen if providing a bug report.

I wanted to run `molecule converge` multiple times to make sure that my idempotent thing was working, and that the playbook would succeed. I can get a successful first run to work, but subsequent runs fail with `8989 Bus Error` then after that following converges stall out on the failed portion. 

# Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](https://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

[Molecule Debug Output listed here.](https://gist.github.com/predatorian3/4cf986e20fea78410d6e5df8348e87cf#file-molecule_debug_converge-log-L4405-L4434)

**Comment by lwm** [comment]
Hey @predatorian3, thanks for the report.

> I wanted to run molecule converge multiple times to make sure that my idempotent thing was working,

JFYI, `molecule idempotence` re-runs `molecule converge` for you and compares task results. So, running converge multiple times shouldn't make a difference (since it is done for you). That's the idea anyway :sweat_smile: 

Anyway, this feels like something gone awry in the VM that Vagrant is managing. It's hard to give any further information here but I can recommend: can you `molecule login` into the instance and run the command that the task was trying to do? What is the output? Also, perhaps there is something going wrong in the tear down of the VM - have you tried running `molecule converge --destroy=never` multiple times? Does it succeed?

Any more information would be very welcome here! Hope it helps ...

**Comment by decentral1se** [comment]
OK, pushing off 2.21 right now as we try to slim down the backlog.

Not sure how to push this forward without more Vagrant related feedback.

**Comment by ssbarnea** [comment]
Molecule Vagrant driver was moved to https://github.com/pycontribs/molecule-vagrant/issues and if this issue is still valid, please raise a ticket there. Thanks.
