### ISSUE TITLE
molecule idempotence fails on travis, but passes locally

### ISSUE THREAD

**Issue by Duckle29** [ansible/molecule#1737]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
ansible 2.7.7
molecule 2.19.0
```

Molecule installation method:
- pip

Ansible installation method:
- OS package

Detail any linters or test runners used:

# Desired Behavior

A successfull local `molecule test` with idempotence should also be successfull on travis CI

# Actual Behaviour

The Travis CI build fails on idempotency step, while the local test passes fine.

https://travis-ci.org/Duckle29/ansible-dhparam/builds/491049148

Here's a local run: http://paste.ubuntu.com/p/xjgRfrqmwF/

**Comment by lwm** [comment]
Hi @Duckle29, I had to search for your task definitions and I think I've found them over at https://github.com/Duckle29/ansible-dhparam/blob/master/tasks/main.yml. I would assume your issue is in `when` conditional defined at https://github.com/Duckle29/ansible-dhparam/blob/master/tasks/main.yml#L31. This is most likely not doing what you think it should be doing on the Travis environment. I would start by outputting a debug statement for the output of that.

Overall, all the `idempotence` command is doing is running a regex match against the output of the ansible commands: https://github.com/ansible/molecule/blob/master/molecule/command/idempotence.py#L113. So, if Ansible reports changed, Molecule reports an idempotence failure. So, mostly, problems with idempotence go back to the task definition (but I don't totally rule out a bug in the Molecule implementation).

Hope that helps.

**Comment by Duckle29** [comment]
@lwm Indeed that line didn't do what I wanted it too. For some reason, the openssl output on travis was different than the molecule tests I ran locally, so the SED failed.

I think I messed up wich centOS I tested on locally, so not a molecule mistake. Wrong SED on my part :)
