### ISSUE TITLE
Move https://github.com/retr0h/cookiecutter-molecule

### ISSUE THREAD

**Issue by gundalow** [ansible/molecule#1747]
# Issue Type

- Bug report

# Desired Behavior

https://github.com/retr0h/cookiecutter-molecule.git should be copied inside of github.com/ansible so that we don't depend on external resources

**Comment by themr0c** [comment]
This cookiecutter template, as used by the tests, is the causing all current build fail, because ansible-lint 4.1.0 introduced new rules.

The failing tests are all using the  cookiecutter  template:

- in functional tests - shard 1 tests:  test/functional/docker/test_scenarios.py::test_command_init_role_inspec https://travis-ci.com/ansible/molecule/jobs/177611543 
- in fucntional tests - shard 2, the failing test is test/functional/docker/test_scenarios.py::test_command_init_role_with_template -- see https://travis-ci.com/ansible/molecule/jobs/177611544
- in functional tests - shard 2, the failing test is test/functional/docker/test_scenarios.py::test_command_init_role_goss -- see https://travis-ci.com/ansible/molecule/jobs/177611545

```
$ cookiecutter gh:retr0h/cookiecutter-molecule
role_name [role_name]: test-init
scenario_name [default]: 
author [your name]: 
description [your description]: 
company [your company (optional)]: 
Select license:
1 - BSD
2 - MIT
3 - GPLv2
4 - GPLv3
5 - Apache
6 - CC-BY
Choose from 1, 2, 3, 4, 5, 6 [1]: 
min_ansible_version [1.2]: 
```

```
cd test-init/
```

```
ansible-lint .
[701] Role info should contain platforms
/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml:2
{'meta/main.yml': {'galaxy_info': {'author': 'your name', 'description': 'your description', 'company': 'your company (optional)', 'license': 'BSD', 'min_ansible_version': 1.2, 'galaxy_tags': [], '__line__': 3, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}, 'dependencies': [], '__line__': 2, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}}

[703] Should change default metadata: author
/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml:2
{'meta/main.yml': {'galaxy_info': {'author': 'your name', 'description': 'your description', 'company': 'your company (optional)', 'license': 'BSD', 'min_ansible_version': 1.2, 'galaxy_tags': [], '__line__': 3, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}, 'dependencies': [], '__line__': 2, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}}

[703] Should change default metadata: description
/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml:2
{'meta/main.yml': {'galaxy_info': {'author': 'your name', 'description': 'your description', 'company': 'your company (optional)', 'license': 'BSD', 'min_ansible_version': 1.2, 'galaxy_tags': [], '__line__': 3, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}, 'dependencies': [], '__line__': 2, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}}

[703] Should change default metadata: company
/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml:2
{'meta/main.yml': {'galaxy_info': {'author': 'your name', 'description': 'your description', 'company': 'your company (optional)', 'license': 'BSD', 'min_ansible_version': 1.2, 'galaxy_tags': [], '__line__': 3, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}, 'dependencies': [], '__line__': 2, '__file__': '/home/.ecryptfs/src/externals/themr0c/test-init/meta/main.yml'}}

```

=> same issue with ansible-lint 4.0.1 and 4.1.0
=> no issue with  ansible-lint 3.5.1

As we want to move forward to ansible-lint 4.1.0,  while moving  the cookiecutter template, we should ensure that it is used in the tests with non-default values for author, description, company, and that the platforms are defined:

- [701] Role info should contain platforms
- [703] Should change default metadata: author
- [703] Should change default metadata: description
- [703] Should change default metadata: company

**Comment by themr0c** [comment]
[701] Role info should contain platforms => we need to work on that file which does not template platform: https://github.com/retr0h/cookiecutter-molecule/blob/master/%7B%7Bcookiecutter.role_name%7D%7D/meta/main.yml

So this ticket becomes a blocker for 2.20.

@gundalow can we have some gh/ansible/molecule-cookiecutter ?

**Comment by gundalow** [comment]
@themr0c done https://github.com/ansible/molecule-cookiecutter

**Comment by ssbarnea** [comment]
Why creating a new repository when we could host the cookiecutter inside molecule itself? This could save a serious amount of time especially as we test it durin build. 

Why to risk someone pushing a change to cookiecutter project and break molecule when we can prevent it from start?

**Comment by themr0c** [comment]
I don't know how the cookiecutter files would be distributed at regular install time of molecule. I guess the current state was adressing this issue: the same command `cookiecutter gh:retr0h/cookiecutter-molecule` is used in the documentation and in the tests? I am not religious about one or another solution.

**Comment by lwm** [comment]
Local template would be nice but it's a fairly big change (need to write `MANIFEST.in`, include the template sources and then implement some inspect logic to find them on the users system) and I am not sure we want to handle that logic at all in Molecule? Let's rely on the network for now? We certainly need to be careful about updating the template, good point!

**Comment by lwm** [comment]
Handled in https://github.com/ansible/molecule/pull/1749!
