### ISSUE TITLE
improve testing experience for developers

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1752]
Currently running molecule test suite locally seems to be a real challenge because the old approach of cloning and just running `tox` does not work at all. 

If you are lucky this will run succefully linting and unit tests but will likely give you 99% failure rase on functional tests and not without waiting many minutes for them to run.

Functional testing should be made smart: like detecting which drivers are available and configured on current platform and use only these, skipping all the tests that cannot be performed because your current system does not have the prerequisites for testing them (like missing tools or credentials).

On CI the auto-detection would be disabled as we do not want to accidentaly skip tests just because some credentials were changed or something similar. Still, for development machines the default behaviour should be to tests "whatever can be tested".

I am fully aware that user can define his own `TOXENV` variable to limit what is run, still this does not cover for different drivers, which may not exist on his machine (example lxc is not available on MacOS).

Maybe we should also consider a different matrix split of testing by driver instead of having unit/functional. We could run unti and functional in the same environment (sequential?) but we should probably split by driver. As a user I find extremely useful to do something like `tox -e py27-ansible25-docker`.

Most developers withh not have credentials for all the supported platforms, likely they will have *none* and just rely on the two non cloud drivers.

- [ ] Coverage report is kinda useless/spammy for developer usage, should not be disabled on non CI usage
- [ ] Why we really need rubocop? Can we avoid it as it introduces a testing dependency on ruby which is quite problematic for at least two platforms MacOS and CentOS-7 where is far from easy to install.
- [ ] Consider using a Makefile or bash script for testing because this could be used to test and eventually install build-prerequisites for each platform. While writing bash could be easier I am inclined to believe that a Makefile could make easier to maintain long term (can provide help here).
- [ ] Replace complex development environment instructions with a simple command like "make bootstrap". The script could replace documentation and users could make PRs to improve it.
- [ ] Consired recording system package dependencies inside [bindep.txt](https://pypi.org/project/bindep/) instead of docs.

Undocumented tricks for easing local testings:
```
export TRAVIS=1
export CI=1
export PYTEST_ADDOPTS="-x --no-cov"
```
First two lines would disable any non-docker tests and the last one will fail on fast on first failure and avoid doing coverage and its reports. Maybe we can find a way to make these implicit for developers.

**Comment by lwm** [comment]
Important points! Thanks for raising. We'll have to try and make this work better for ourselves indeed.

**Comment by webknjaz** [comment]
> Functional testing should be made smart: like detecting which drivers are available

FTR the starting point for this is probably https://github.com/ansible/molecule/blob/358c247/test/functional/conftest.py#L267-L379

> Maybe we should also consider a different matrix split of testing by driver instead of having unit/functional. [...] As a user I find extremely useful to do something like `tox -e py27-ansible25-docker`.

Yes and no. I think we probably don't need to have a lot of copy-pasted sections in `tox.ini` (I'd like to make it more easily maintainable) but on the other hand it should probably be possible with defining factor-based `PYTEST_ADDOPTS` env var. Which could be smth like:
```ini
[testenv]
setenv =
  [...]
  docker: PYTEST_ADDOPTS="-k docker"
```
(this needs someone to investigate it, I didn't test whether it works but it could make `tox` work just as you want from the UI perspective)

> Coverage report is kinda useless/spammy for developer usage, should not be disabled on non CI usage

Did you mean "should" or "should not"?

> * Why we really need rubocop?

Is it needed for all tests? AFAIK it's some linter integration. Of course, as Pythonistas, we often don't like Ruby. But what if somebody in the wild depends on it?

Also, maybe DIND would address this?

> * Makefile

I usually discorage using this thing in Python project. First of all, it's too many layers of abstraction and +1 technology to understand. Second, it'd duplicate most of what we have in `tox.ini` and will be just a proxy but limiting access to `tox`'s own features because you cannot easily do `make -- -k test_only_this`. It's also not python-aware: while it's fine for projects in C, there's much more to it in Python, like virtualenv and stuff.
And finally, you can do everything in `tox.ini` having (1) unified tool for describing test/build/related workflows + it's also a single medium for having things/envs shared with different CIs.

>  Replace complex development environment instructions with a simple command like "make bootstrap". The script could replace documentation and users could make PRs to improve it.

I'd prefer `tox -e bootstrap`, especially looking at how this tool has been hugely improved lately...

> * Consired recording system package dependencies inside [bindep.txt](https://pypi.org/project/bindep/) instead of docs.

This definetely sounds interesting! May I be the one who'd point out that Ansible can do that? :)

**Comment by themr0c** [comment]
> Why we really need rubocop? Can we avoid it as it introduces a testing dependency on ruby which is quite problematic for at least two platforms MacOS and CentOS-7 where is far from easy to install.

`Rubocop` dependency was introduced to produce a feature complete Docker image: it is needed by the `Inspec` verify backend.

**Comment by ssbarnea** [comment]
@themr0c I do not know all the details but I am wondering if we could not maybe use a dockerized version of rubocop in order to perform this verifications, so we would avoid adding ruby as a development requirements (docker is already a requirements)

**Comment by decentral1se** [comment]
https://github.com/ansible/molecule/pull/1870#issue-263559863 makes it possible to run `tox -e functional` and only get the Docker based functional tests running without anything further to manage. We still install all the test extras but that is for another time ...

**Comment by decentral1se** [comment]
Question: how do we conditionally skip tox installing driver dependencies? With https://github.com/ansible/molecule/pull/1870, we can skip the driver tests but we still install the dependencies for them. Is there some "not magic" way of doing this that doesn't further complicate our Tox configuration?

**Comment by decentral1se** [comment]
Rumour has it, experience is being improved: https://github.com/ansible/molecule/pull/1870#pullrequestreview-221231559 :)

**Comment by ssbarnea** [comment]
We should at least install dependencies for each driver on CI, even if we do not test them at this moment because this would allow us to test conflicts with them. There is a lot of value of just installing requirements on various combinations of extras. Maybe we could do this in a special tox environment?

**Comment by decentral1se** [comment]
OK, that sounds fine. We're already installing them for functional tests, so we're covered.

The issues on this ticket are a bit out of date now, shall we close / edit the initial description? For example:

> Coverage report is kinda useless/spammy for developer usage, should not be disabled on non CI usage

Not an issue any more, see the testing.rst documentation which shows running tests without coverage.

> Why we really need rubocop? Can we avoid it as it introduces a testing dependency on ruby which is quite problematic for at least two platforms MacOS and CentOS-7 where is far from easy to install.

Still an issue but not a major one since it is skipped by default now anyway ...

> Consider using a Makefile or bash script for testing because this could be used to test and eventually install build-prerequisites for each platform. While writing bash could be easier I am inclined to believe that a Makefile could make easier to maintain long term (can provide help here).
> Replace complex development environment instructions with a simple command like "make bootstrap". The script could replace documentation and users could make PRs to improve it.

Seems we're standardising on Tox.

> Consired recording system package dependencies inside bindep.txt instead of docs.

We have a `bindep.txt` now.

**Comment by decentral1se** [comment]
Just running `tox` now actually works, so I would consider that we've achieved the scope of this ticket.

**Comment by decentral1se** [comment]
I'm going to optimistically close this out since we're in the WG now and trying to slim down issues from the backlog. As I've mentioned above, I think we've made solid progress in this regard and further needs can be documented in more focused issues.
