### ISSUE TITLE
Add change log entries for v2.20 release

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#1772]
This is a bit painful and unfortunate that we've been missing the entries.

We should add entries for user facing changes for the next release.

See https://github.com/ansible/molecule/projects/2 for more.

**Comment by webknjaz** [comment]
How about using `towncrier` or `reno` for that?

**Comment by decentral1se** [comment]
I really like the look of `towncrier`! Any reasons to chose one over the other? I'm open!

Here's the user facing changes/fixes/etc. that I see from https://github.com/ansible/molecule/projects/2:

* https://github.com/ansible/molecule/pull/1606/
* https://github.com/ansible/molecule/pull/1545
* https://github.com/ansible/molecule/pull/1538
* https://github.com/ansible/molecule/pull/1536
* https://github.com/ansible/molecule/pull/1720
* https://github.com/ansible/molecule/pull/1593
* https://github.com/ansible/molecule/pull/1683
* https://github.com/ansible/molecule/pull/1555
* https://github.com/ansible/molecule/pull/1640
* https://github.com/ansible/molecule/pull/1635
* https://github.com/ansible/molecule/pull/1685
* https://github.com/ansible/molecule/pull/1684
* https://github.com/ansible/molecule/pull/1674
* https://github.com/ansible/molecule/pull/1728
* https://github.com/ansible/molecule/pull/1717
* https://github.com/ansible/molecule/pull/1703
* https://github.com/ansible/molecule/pull/1458
* https://github.com/ansible/molecule/issues/1747
* https://github.com/ansible/molecule/pull/1771
* https://github.com/ansible/molecule/pull/1765

I probably missed some and there have been looaaddsss more work done on internals of project maintenance! I probably won't have time to compile this today into the `CHANGELOG.md` but will later in the week. Hoping to see movement on a pre-release today if not this week! :+1:

**Comment by webknjaz** [comment]
@decentral1se you can do a pre-release `v2.20a0` and then release a follow-up pre-release `v2.20a0.post0` as soon as you're done with changelog. It should be that flexible.

P.S. See https://www.python.org/dev/peps/pep-0440/#post-releases for chaining sub-release versions details

**Comment by webknjaz** [comment]
Regarding automation.

I've got several projects using `towncrier` and it's very easy to use, yet it's got some limitations (I think it's one-lined markdown so it's usually one sentence, IIRC).

Ansible uses `reno`. It's way more complicated. Users have to add YAML files with proper keys instead of adding just files with extensions and text. It's also challenging to integrate, I was trying to do it for virtualenv or tox (I don't remember) a while back but failed, which feels discoraging. OTOH, Ansible has a wrapper script for running log generation.
It is an OpenStack project and seamlessly integrates with pbr and SphinX.

So I vote for towncrier as it's simpler. Unless anyone has other opinions, I'd like to avoid reno. Otherwise, somebody else will have to figure out the integration part.

**Comment by decentral1se** [comment]
TODO https://github.com/ansible/molecule/pull/1797#discussion_r261882101

**Comment by decentral1se** [comment]
RE: automation, see https://github.com/ansible/molecule/issues/1779#issuecomment-470255441.

We'll compile this manually for v2.20 :+1: 

See latest WG logs.

**Comment by decentral1se** [comment]
Taken a stab at this in https://github.com/ansible/molecule/pull/1816!
