### ISSUE TITLE
Use Towncrier/Reno to automate the change log

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#1779]
See https://github.com/ansible/molecule/issues/1772#issuecomment-467204991 :+1: 

It's still open for discussion but I defer to @webknjaz on this one. If no one else objects, we can go with it!

**Comment by ssbarnea** [comment]
AFAIK pbr can also deal with changelogs, something we need to check.

If pbr does not cover it maybe `reno` sounds better because: we leverage a tool already used by ansible. Even if towncrier is better we may be better of leveraging the already known/used tools and avoid introducing new potention source of issues.

One exception would be if we already get signals that a migration is happening from ansible too.

**Comment by webknjaz** [comment]
@ssbarnea I've mentioned this in that comment that is linked: reno can be integrated with sphinx and pbr. But I dislike it because `reno` is hard/unobvious to integrate and I still want to get rid of `pbr` anyway.

FTR I think towncrier is better known in Python community in general (except for openstack folks maybe).

**Comment by decentral1se** [comment]
OK, based on latest WG, we've got some weight behind using Reno. Please check the logs.

@pabelanger has kindly offered to do a small show and tell and let's see what is what :)

**Comment by webknjaz** [comment]
@pabelanger we'll need to see how it works with `pbr` removed.

**Comment by decentral1se** [comment]
I'm going to take a stab at towncrier integration. Pytest/tox use it.

**Comment by webknjaz** [comment]
Good luck. You'll need it. I've failed to configure `reno` once a per required expectations. So if you have another 10 minutes to spare please also look at `towncrier` config just to feel the difference in approaches and expectations it brings :)

**Comment by webknjaz** [comment]
Oh, and ping me once you decide on the changelog fragments location. I want to integrate a check for PRs. It looks like: https://github.com/sanitizers/browntruck/pull/3/checks?check_run_id=78558955

**Comment by decentral1se** [comment]
Read it again :)

**Comment by webknjaz** [comment]
Oh... My eyes are failing me :)

**Comment by webknjaz** [comment]
But anyway it's a good experience to try both for the person doing the integration anyway.

**Comment by decentral1se** [comment]
Bikeshed alert https://github.com/ansible/molecule/pull/1963 !

**Comment by webknjaz** [comment]
https://github.com/ansible/molecule/pull/1979#discussion_r278106413

**Comment by decentral1se** [comment]
Won't have time to chase this.
