### ISSUE TITLE
Evaluate upgrading to testinfra 2.0.0

### ISSUE THREAD

**Issue by seandst** [ansible/molecule#1849]
testinfra 2.0.0 is available. The current requirement is for 1.1.9, which by semver indicates backward-incompatible changes. Those changes, according to testinfra's [changelog](https://github.com/philpep/testinfra/blob/master/CHANGELOG.rst#200), are:

```
- Drop deprecated "testinfra" command, you should use "py.test" instead
- Drop deprecated top level fixtures, access them through the fixture "host" instead.
- Drop support for ansible <= 2.4
```

The change to the testinfra command should not break molecule's integration with testinfra, as molecule uses py.test, as directed by testinfra.
The change removing the top level fixtures may break molecule _users_, but they have been deprecated since testinfra 1.6, released in April of 2017.
The change dropping support for ansible <= 2.4 does not affect molecule (molecule requires ansible >=2.5).

**Comment by decentral1se** [comment]
Thanks for raising @seandst!

> The change removing the top level fixtures may break molecule users, but they have been deprecated since testinfra 1.6, released in April of 2017.

I wonder how we should deal with this with regard to versioning ... does a change log entry suffice!?

**Comment by philpep** [comment]
Hi, I'm the maintainer of testinfra.

Indeed the change which may affect your users for 2.0.0 is the removal of old fixtures ``Command``, ``Package``, but DeprecationWarnings are issued since 1.6 and IIRC since recent pytest releases, I'd say ~ 1 or 2 years ago, these warning are displayed in the output by default.

I think you can even safely pin ``testinfra<3`` here, I have a strong policy regarding API changes using semver X.Y.Z where Z is bugfix, Y new feature without breaking changes (mostly new interfaces and backends to introspect systems) and X is major release dropping deprecated stuff. Probably the version 3 will drop python2 support or introduce a new ansible backend based on https://github.com/ansible/ansible-runner

I think we can do this without breakage, but you known it's python and users might write monkeypaches or rely in deep in the testinfra/ansible api so  ¯\_(ツ)_/¯

In all cases I'd recommend to not pin a specific version because users might want to pin their version and avoid a pkg_resources VersionConflict. Also they probably expect to have a version matching "latest" documentation on readthedocs.

**Comment by seandst** [comment]
> I wonder how we should deal with this with regard to versioning ... does a change log entry suffice!?

I think a change log entry does the job, yeah.

**Comment by decentral1se** [comment]
I've opened up https://github.com/ansible/molecule/pull/2034 against this.
