### ISSUE TITLE
Improve module argument handling

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#1880]
The current situation is that we are increasingly getting requests to add keys from our schema definition in the `molecule.yml` that correspond to the default Docker driver `create.yml`. See https://github.com/ansible/molecule/issues/1879 and https://github.com/ansible/molecule/issues/1878 for more recent examples. This stands for all the driver plays that we maintain.

The problem here is that we are duplicating the effort of what Ansible is doing. We are defining a schema using http://docs.python-cerberus.org/en/stable/ and validating what we get as input. Ansible already does this with the argspec validation. Our schema's can always be be behind in terms of what key/vals they offer ...

Following the idea from https://github.com/ansible/proposals/issues/39#issuecomment-467030338, I would propose the idea for discussion: we somehow move to replace the Cerberus schema definitions with Ansible argspec validation (yet to be finished for external use, but fine to discuss for now).

This would allow us to:
  * Not maintain schemas for Ansible module key/vals
  * Not maintain validation for these schemas
  * Rely on Ansible module argument validation all the way down ...

Questions:
  * Is it feasible to use this argspec validation API here in Molecule?
  * How to manage importing and multiple Ansible versions!?

I'm writing this a bit fast and off the cuff but hopefully it's clear ...

**Comment by decentral1se** [comment]
Example of our Molecule schema: https://github.com/ansible/molecule/blob/master/molecule/model/schema_v2.py#L601. Example of what Ansible is doing: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_container.py#L2859

**Comment by rockandska** [comment]
Not really related as discuss on IRC but think it is complementary, please find an example [here](https://github.com/rockandska/repro-issues/tree/master/molecule/molecule/issue_1880) of how i see a docker molecule.yml who is:
- more readable by avoiding some repetitions regarding the registries / hosts / network parameters
- not stick to the args predefined in molecule, the user have a full access to the module args but molecule could override some parameters (like in the example). (solve #1879 , #1878 ...)
- images managed by molecule have a unique tag (uuid based on image description + dockerfile generated) and we'll be not rebuilt each time a test is launch. (solve #1847, should solve #1688, and partially #1573 )
- dynamic instances names is here but not functional since it is not the parameter "name" use with docker_container that is used in the inventory but "platforms[x].name", same problem if we want to add to the name an uuid corresponding to the current scenario ( partially solve #1573, #1704  )
- not implemented yet, but a "random" option could be add to create the instances randomly on docker_host listed in driver.hosts
- only the networks managed by molecule are deleted ( solve #1817 )

Hope you will find some interesting ideas here.

**Comment by decentral1se** [comment]
Won't have time to chase this.
