### ISSUE TITLE
[FR] Add a standard docker diff - with stdout for test results

### ISSUE THREAD

**Issue by JJediny** [ansible/molecule#1893]
# Issue Type
- Feature request

# Molecule and Ansible details
NA

Molecule installation method (one of):
NA

Ansible installation method (one of):
NA

# Desired Behavior
When using Docker driver, this feature would allow a user to run [docker diff](https://docs.docker.com/engine/reference/commandline/diff/) on all controlled containers to output what's changed for each container.

**Please give some details of the feature being requested**
As a user, sometimes I just want a quick check of what files have been:
1. Added (and their current path on the system)  
2. Modified
3. Deleted 

using this as a simple validation of the impact of the ansible role. When running on multiple OS distros for the ansible tasks/roles, and allow for quick comparison of file paths across multiple platforms when a role supports more than one distro.

**Comment by JJediny** [comment]
may be best as an option: in docker driver enable in the schema this added var/parameter - something like `diff: true` with a default flag as its neither a side effect or verifier. To run a docker diff using the docker containers provisioned by molecule.

**Comment by decentral1se** [comment]
Hey @JJediny, interesting idea. 

This "diff" command would only be availabe for the Docker driver, so I am unsure what the API (command line or otherwise) would look like. Our command line interface is very generic in this way (an advantage, I believe).

I am wondering, you can already run `docker diff instance` (finding the instance name from where you defined in the `molecule.yml`, `docker ps` or `molecule list`) so wondering what is the advantage of adding more functionality for this?

**Comment by JJediny** [comment]
Yes submitted the issue before trying to make it work, and realized its easiest just to run `molecule converge` then `docker ps` then `docker diff containerid`.
