### ISSUE TITLE
Broken unit test: `{'driver': [{'provider': [{'name': ['unallowed value None',`

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2022]
See https://travis-ci.com/ansible/molecule/jobs/196973204#L1232. Saw this on latest CI run of the Hetzner driver PR while rebasing. Remined me of https://github.com/ansible/molecule/pull/1714#pullrequestreview-230537350. Not sure of cause ...

Anyone got time for this?

> 
> =================================== FAILURES ===================================
> _ test_driver_provider_name_not_nullable_when_vagrant_driver[_model_driver_provider_name_n...] _
> _config = {'dependency': {'name': 'galaxy'}, 'driver': {'name': 'vagrant', 'provider': {'name': None}}, 'lint': {'name': 'yamllint'}, 'platforms': [{'image': 'centos:latest', 'name': 'instance'}], ...}
>     @pytest.mark.parametrize(
>         '_config',
>         ['_model_driver_provider_name_not_nullable_when_vagrant_section_data'],
>         indirect=True)
>     def test_driver_provider_name_not_nullable_when_vagrant_driver(_config):
>         x = {
>             'driver': [{
>                 'provider': [{
>                     'name': ['unallowed value None', 'null value not allowed']
>                 }]
>             }]
>         }
>     
> >       assert x == schema_v2.validate(_config)
> E       AssertionError: assert {'driver': [{...allowed']}]}]} == {'driver': [{'...allowed']}]}]}
> E         Differing items:
> E         {'driver': [{'provider': [{'name': ['unallowed value None', 'null value not allowed']}]}]} != {'driver': [{'provider': [{'name': ['null value not allowed']}]}]}
> E         Full diff:
> E         - {'driver': [{'provider': [{'name': ['unallowed value None',
> E         ?                                               ----------- ^
> E         + {'driver': [{'provider': [{'name': ['null value not allowed']}]}]}
> E         ?                                      + +++++++++ +++        ^^^^^^
> E         -                                     'null value not allowed']}]}]}

**Comment by micheelengronne** [comment]
The behaviour of this test was already changed twice.

Here https://github.com/ansible/molecule/commit/cd2ea98325bd1a418371eb8a24b0e2a1b5952f05#diff-d3601755c38e1ab64638083914501041

And here https://github.com/ansible/molecule/commit/bd69c6d9af6bc9683fd3eda74f30d9060de878e7#diff-d3601755c38e1ab64638083914501041

There should be more descriptions of this particular unit test as it seems very unstable.

I don't know what is the correct behaviour. The 2 error messages or the one ?

As a personal opinion, there should be only 1 error message "null value not allowed".

Why ? Because 'None' is only a particular case of a more general issue. I don't think 'turlututu' is allowed either, nor 'coincoin'. That means, there should be another logic somewhere to handle all unallowed values and not 'None' specifically.

**Comment by decentral1se** [comment]
Thanks for investigating @micheelengronne! That is much appreciated.

Following your history tracking, I see that the test was changed when [cerberus](http://docs.python-cerberus.org/en/stable/index.html) (schema validation that this tool uses right now ...) was bumped to 1.2. Now I see that Cerberus has made a 1.3 release (see https://pypi.org/project/Cerberus/#history) and now we have this failing test. So, I think this is about Cerberus and the way it is outputting schema validation error messages.

I do not have time to chase this up but whoever cares enough might try to validate my guesses here and perhaps follow up with a ticket on the Cerberus repository. For a more concrete "now" solution for Molecule, I think we should add an upper bound for the minor versions of Cerberus.

**Comment by decentral1se** [comment]
Done in 0277957d544c75ffd361a350ba2796694ec84640.
