### ISSUE TITLE
molecule should not create predictable temp folders in shared location like /tmp

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#2126]
Based on feedback from @abadger, feel free up update it:

> Creating predictably named files and directories is a well known source of CVEs. For instance:
> 
>     https://linuxsecurity.com/news/documentation/safely-creating-temporary-files-in-shell-scripts/
>     https://wiki.sei.cmu.edu/confluence/display/c/FIO21-C.+Do+not+create+temporary+files+in+shared+directories
> 

This bug affects only master as it was introduced by https://github.com/ansible/molecule/commit/b44fe7174c9e094b5f122a7511161154a5b6505e

**Comment by rockandska** [comment]
Just want to open a Feature Request related to this but not for the same concern.
Having molecule temporary files residing in /tmp cause 2 behaviour IMO

- having two users working on the same project cause conflict because it use the same /tmp directory
- having molecule files in /tmp cause to lost the actual state when powering off the computer or have a power outage.

but i just realize, since the molecule instances name doesn't contain an uuid based on the project path yet, that it would result to conflict too if two users launch the same scenario

Having molecule temporary files reside in ~/.cache would be a better place to have those files surviving a reboot and solve this issue too.

Regards,
