### ISSUE TITLE
Don't be blocked on making a new release by failure on the ansible devel job

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2204]
When did this become the case? I have no idea. 

We need to remove this restriction.

**Comment by ssbarnea** [comment]
I am against this proposal. In fact I would be more likely to drop support for oldest ansible in module than not testing our code with ansible-devel.

Despite historical experience, Ansible has not much better test coverage and they do not introduce random changes in devel. That is our chance of preventing a failure, before is released.

In fact my recent PR was to to enable execution of devel all the time, so we do not break molecule releases because we forgot to test on devel.

I personally think that we are better off with a (N-1,N+1) support model than with the `(N-2,N)` one but such decision is not be made by me alone.

**Comment by decentral1se** [comment]
> not testing our code with ansible-devel.

That's not the proposal.

This about continuing to test against ansible devel but not making it a blocking issue for releases.

**Comment by decentral1se** [comment]
> In fact my recent PR was to to enable execution of devel all the time, so we do not break molecule releases because we forgot to test on devel.

See https://github.com/ansible/molecule/pull/2205#issuecomment-518555152.

**Comment by decentral1se** [comment]
Don't care anymore.
