### ISSUE TITLE
Opennebula as driver for vagrant

### ISSUE THREAD

**Issue by mikhailsamoylov** [ansible/molecule#2226]
# Issue Type

- Feature request

Hello.
Is it possible to use https://opennebula.org/ as vagrant driver instead libvirt, virtualbox?
Its supports by Vagrantfile if I provide in Vagrantfile options like: config.vm.provider: opennebula
But if I try to configure my vagrant driver with provider: opennebula I got Validation schema error.

**Comment by decentral1se** [comment]
Hi @mikhailsamoylov, we're in the process of making it such that anyone can implement whatever driver they need outside of the core development (plugin architecture). If the patch is small to add a new provider then I would not be totally against it but otherwise, let's hold out until the plugin work gets further.

**Comment by ssbarnea** [comment]
Look at https://github.com/pycontribs/molecule-azure and feel free to implement it. From now on all drivers will be developer in their own repositories.
